### ISSUE TITLE
Instructions for AHZmoreHUDPlugin.dll crash

### ISSUE THREAD

**Issue by pbxs666** [ahzaab/moreHUDSE#63]
I saw a friend in the bug feedback that he would randomly ctd, and his error log information is similar to mine (see below), which is caused by AHZmoreHUDPlugin.dll.
The reason is that I think it has something to do with ostim or osa+osex. After a lot of testing by myself, when I don't enter the sex scene of ostim, everything is normal in the game. Once the sex scene starts or just ends, the game will freeze within a few minutes. , followed by ctd.
[Crash_2022_4_12_23-40-3.txt](https://github.com/ahzaab/moreHUDSE/files/8480238/Crash_2022_4_12_23-40-3.txt)
[Crash_2022_4_13_17-20-44.txt](https://github.com/ahzaab/moreHUDSE/files/8480241/Crash_2022_4_13_17-20-44.txt)

Thank you very much for making this morehud, it works very well, but it conflicts with ostim at this stage, I will wait for your update, thank you!

skyrim: 1.5.97 SE
morehud: 4.0.0.6
ostim: 5.4

**Comment by pbxs666** [comment]
https://github.com/ahzaab/moreHUDSE/issues/62

I have read all 8 crash logs in this feedback report. There are osa and ostim in the all load list, and there is sexlab in them also, but it should be ok with the traditional sexlab

**Comment by pbxs666** [comment]
After a more accurate test, it is found that it is related to the weapon. As long as the ostim scene is started, in the subsequent game process, as long as morehud detects the weapon item, it will ctd.

**Comment by pbxs666** [comment]
This time I found the source.
1. First talk about how I tested:
After opening the game and reading the archive, the cross pointer is aimed at the weapon in the scene, no problem. Start the sex scene "player to npc", end the sex, align the cross pointer with the weapon, ctd.
Sex scene only "player to npc" will cause ctd, "npc to npc" no problem. It doesn't matter if sex is actively triggered or passively triggered.
It may be that ostim has changed some values ​​of the character after sex, or it may be a bug of morehud.
The sex data of ostim will not be saved in the archive, so after the game ctd, start the game again, picking up weapons will not ctd.

2. The root of the problem is here: in the mcm menu of morehud, there is a function "display player data": the function of displaying the weight and the number of gold coins in the lower right corner of the screen. As long as it is turned off, there will be no ctd when the weapon is selected after ending the sex scene. If you have to turn on this function, you cannot select weapons in the scene after the sex scene ,otherwise It will ctd(the backpack interface will not be affected, and using "quick loot" to take weapons from the box will not affect it, the plugin maybe depend on the backpack system). In addition, the "whether to show weight change" function will not cause ctd, it has nothing to do with it.

3. I guess it is related to the calculation of the character's attack value (although I tested a weapon in the selected scene before the sex scene, the damage value increase and decrease were calculated correctly, but after the sex scene, the calculation of the attack value will be ctd).

4. And I found that the value calculation of the armor of the morehud MOD is wrong, but it will not cause ctd (MOD only calculates the armor value of the equipment in the regular slot, and does not calculate the armor value of the special slot of the widget, especially the MOD Clothing will generally have a large number of widgets, miscellaneous equipment, occupying unconventional slots) If MOD clothing is equipped, the armor value calculation may be wrong.

**Comment by ahzaab** [comment]
Thanks for the extra info.  Unfortunately I do not support those mods at this time.  I'll see what I can do, but no eta.

**Comment by pbxs666** [comment]
> Thanks for this information mate it was a really interesting read. Do you have any suggestions on fixing the issue besides the mods being updated?

I suggest you first test it in the game according to my method to see if the crash conditions are the same. Pay attention to ostim and weapons, I noticed you have sex mods installed too
If it is the same, you can follow the temporary solution I mentioned above, that is: turn off the function of displaying the gold coin load in the lower right corner of morehud, which can be solved.

**Comment by ahzaab** [comment]
Please test with this build: https://github.com/ahzaab/moreHUDSE/releases/download/4.1.0-SE/AHZmoreHUDPlugin.dll

**Comment by ahzaab** [comment]
> > Please test with this build: https://github.com/ahzaab/moreHUDSE/releases/download/4.1.0-SE/AHZmoreHUDPlugin.dll
> 
> Unfortunately, still CTD

Can you paste a crash log for this version please?

**Comment by pbxs666** [comment]
> > > Please test with this build: https://github.com/ahzaab/moreHUDSE/releases/download/4.1.0-SE/AHZmoreHUDPlugin.dll
> > 
> > 
> > Unfortunately, still CTD
> 
> Can you paste a crash log for this version please?
[Crash_2022_5_16_23-11-55.txt](https://github.com/ahzaab/moreHUDSE/files/8701382/Crash_2022_5_16_23-11-55.txt)
Sorry for not uploading the crash log in time.
A few days ago, I tested found that the crash log was very similar to the previous ones, so I didn't upload it.

Today, I specifically opened Skyrim to test with the previous method, and I found an unexpected discovery: the save file I tested has disabled the function of displaying player data (gold coins, weight) in morehud by default. After finishing the ostim scene, select the weapon object in the scene, and there is no CTD. 
Enter MCM to open morehud's display player data function, but there is no CTD at this time!!! Then re-enter and end the sex scene, the cursor is aimed at the weapon item on the ground, and CTD occurs.

**Comment by ahzaab** [comment]
Thanks.  I needed the new crash log for the actual address.

**Comment by ahzaab** [comment]
@pbxs666 I found an issue at the address from the crash log.  Please try this version out and let me know how it goes: https://github.com/ahzaab/moreHUDSE/releases/download/4.1.1-SE/AHZmoreHUDPlugin.dll

**Comment by pbxs666** [comment]
> @pbxs666 I found an issue at the address from the crash log. Please try this version out and let me know how it goes: https://github.com/ahzaab/moreHUDSE/releases/download/4.1.1-SE/AHZmoreHUDPlugin.dll

Thank you very much, there will be no CTD this time.
Curious how ostim caused this bug?🤔
